"""persona profile

Revision ID: 20bceff0690e
Revises: 66be7bc08a2f
Create Date: 2026-09-04 15:12:53.555448
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel autogenerate가 AutoString 등을 참조하므로 필요
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20bceff0690e"
down_revision: str | None = "66be7bc08a2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persona_communication_style",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("persona_id", sa.Uuid(), nullable=False),
        sa.Column("tone", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "sentence_length",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "question_style",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.Column("directness", sa.Integer(), nullable=False),
        sa.Column(
            "empathy_expression",
            sqlmodel.sql.sqltypes.AutoString(length=200),
            nullable=False,
        ),
        sa.CheckConstraint(
            "directness BETWEEN 1 AND 5", name="ck_communication_style_directness"
        ),
        sa.PrimaryKeyConstraint("persona_id"),
    )
    op.create_table(
        "persona_core_value",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("persona_id", sa.Uuid(), nullable=False),
        sa.Column("core_value_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "persona_id", "core_value_id", name="uq_persona_core_value"
        ),
        sa.UniqueConstraint(
            "persona_id", "priority", name="uq_persona_core_value_priority"
        ),
    )
    op.create_index(
        op.f("ix_persona_core_value_core_value_id"),
        "persona_core_value",
        ["core_value_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_persona_core_value_persona_id"),
        "persona_core_value",
        ["persona_id"],
        unique=False,
    )
    op.create_table(
        "persona_core_value_vocab",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "value_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("value_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persona_core_value_vocab")
    op.drop_index(
        op.f("ix_persona_core_value_persona_id"), table_name="persona_core_value"
    )
    op.drop_index(
        op.f("ix_persona_core_value_core_value_id"), table_name="persona_core_value"
    )
    op.drop_table("persona_core_value")
    op.drop_table("persona_communication_style")
    # ### end Alembic commands ###
