"""chat room

Revision ID: 66be7bc08a2f
Revises: e2b6cc0b1fd8
Create Date: 2026-09-04 13:29:46.342485
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel autogenerate가 AutoString 등을 참조하므로 필요
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66be7bc08a2f"
down_revision: str | None = "e2b6cc0b1fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_room",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("persona_id", sa.Uuid(), nullable=False),
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "thumbnail_url", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True
        ),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_room_host_id"), "chat_room", ["host_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_room_persona_id"), "chat_room", ["persona_id"], unique=False
    )
    op.create_index(op.f("ix_chat_room_status"), "chat_room", ["status"], unique=False)
    op.create_index(
        "ix_chat_room_status_created",
        "chat_room",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_chat_room_live_persona",
        "chat_room",
        ["persona_id"],
        unique=True,
        postgresql_where=sa.text("status = 'live'"),
        sqlite_where=sa.text("status = 'live'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_chat_room_live_persona",
        table_name="chat_room",
        postgresql_where=sa.text("status = 'live'"),
        sqlite_where=sa.text("status = 'live'"),
    )
    op.drop_index("ix_chat_room_status_created", table_name="chat_room")
    op.drop_index(op.f("ix_chat_room_status"), table_name="chat_room")
    op.drop_index(op.f("ix_chat_room_persona_id"), table_name="chat_room")
    op.drop_index(op.f("ix_chat_room_host_id"), table_name="chat_room")
    op.drop_table("chat_room")
    # ### end Alembic commands ###
