"""room broadcast topic

Revision ID: 87fc6658cdca
Revises: b1c7761945fe
Create Date: 2026-09-09 19:34:17.328180
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel autogenerate가 AutoString 등을 참조하므로 필요
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "87fc6658cdca"
down_revision: str | None = "b1c7761945fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `server_default=""`는 autogenerate가 넣어 주지 않는다. 없이 그대로 돌리면
    # **기존 방들 때문에 NOT NULL 추가가 거부된다** — 채울 값이 없기 때문이다.
    #
    # 기본값을 붙인 채로 남겨 둔다(뒤에 떼지 않는다): 주제 없는 방송이 정상이고,
    # 빈 문자열이 곧 "주제 없음"이라 도메인 기본값(`Room.topic = ""`)과 같은 뜻이다.
    op.add_column(
        "chat_room",
        sa.Column(
            "topic",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
            server_default="",
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_room", "topic")
    # ### end Alembic commands ###
