"""community story

Revision ID: a443eb494cdb
Revises: 484a64eef257
Create Date: 2026-09-02 19:49:46.275243
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel autogenerate가 AutoString 등을 참조하므로 필요
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a443eb494cdb"
down_revision: str | None = "484a64eef257"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_story",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("persona_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_anonymous", sa.Boolean(), nullable=False),
        sa.Column(
            "relationship_stage", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("nickname", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_community_story_author_id"),
        "community_story",
        ["author_id"],
        unique=False,
    )
    op.create_index(
        "ix_community_story_persona_created",
        "community_story",
        ["persona_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_community_story_persona_status",
        "community_story",
        ["persona_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_community_story_persona_status", table_name="community_story")
    op.drop_index("ix_community_story_persona_created", table_name="community_story")
    op.drop_index(op.f("ix_community_story_author_id"), table_name="community_story")
    op.drop_table("community_story")
    # ### end Alembic commands ###
