"""chat message transcript

Revision ID: b1c7761945fe
Revises: c3d81b0f5a47
Create Date: 2026-09-08 13:07:24.833952
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel autogenerate가 AutoString 등을 참조하므로 필요
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c7761945fe"
down_revision: str | None = "c3d81b0f5a47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "text", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False
        ),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("persona_id", sa.Uuid(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column(
            "model_version", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("amount", sa.Integer(), nullable=True),
        sa.Column("replied_to", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_message_persona_id"), "chat_message", ["persona_id"], unique=False
    )
    op.create_index(
        "ix_chat_message_room_id_desc",
        "chat_message",
        ["room_id", sa.literal_column("id DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chat_message_room_id_desc", table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_persona_id"), table_name="chat_message")
    op.drop_table("chat_message")
    # ### end Alembic commands ###
