"""wallet + identity is_staff

Revision ID: cb7d29994856
Revises: 259a4a23dd7d
Create Date: 2026-09-03 13:19:48.327035
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # SQLModel autogenerate가 AutoString 등을 참조하므로 필요
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb7d29994856"
down_revision: str | None = "259a4a23dd7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallet_credit_transaction",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ref_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_wallet_credit_transaction_user_created",
        "wallet_credit_transaction",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "wallet_donation",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("persona_id", sa.Uuid(), nullable=False),
        sa.Column("donor_id", sa.Uuid(), nullable=True),
        sa.Column("room_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_donation_donor_id"),
        "wallet_donation",
        ["donor_id"],
        unique=False,
    )
    op.create_index(
        "ix_wallet_donation_persona_created",
        "wallet_donation",
        ["persona_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallet_donation_room_id"), "wallet_donation", ["room_id"], unique=False
    )
    op.create_table(
        "wallet_wallet",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("credit_balance", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "credit_balance >= 0", name="ck_wallet_balance_non_negative"
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # server_default가 필요하다 — 이미 가입한 사용자들에게 채워 넣을 값이 없으면
    # NOT NULL 추가가 실패한다. 기본값은 거짓, 즉 권한은 명시적으로만 준다.
    op.add_column(
        "identity_user",
        sa.Column("is_staff", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("identity_user", "is_staff")
    op.drop_table("wallet_wallet")
    op.drop_index(op.f("ix_wallet_donation_room_id"), table_name="wallet_donation")
    op.drop_index("ix_wallet_donation_persona_created", table_name="wallet_donation")
    op.drop_index(op.f("ix_wallet_donation_donor_id"), table_name="wallet_donation")
    op.drop_table("wallet_donation")
    op.drop_index(
        "ix_wallet_credit_transaction_user_created",
        table_name="wallet_credit_transaction",
    )
    op.drop_table("wallet_credit_transaction")
    # ### end Alembic commands ###
