"""donation ranking index

Revision ID: e2b6cc0b1fd8
Revises: cb7d29994856
Create Date: 2026-09-04 10:04:52.659390
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2b6cc0b1fd8"
down_revision: str | None = "cb7d29994856"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_wallet_donation_persona_donor",
        "wallet_donation",
        ["persona_id", "donor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wallet_donation_persona_donor", table_name="wallet_donation")
    # ### end Alembic commands ###
